### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by easycnn** [supalle/auto-trim#1]
只创建了一个实体类文件，我的代码：
```
@Data
@AutoTrim
public class User3Entity {

    public String username;

    @AutoTrim.Ignored
    public String email;

    public Integer age;
}
```

启动报错：
```
执行预编译任务…
正在运行 'before' 任务
正在检查源
正在复制资源… [spring-boot-mvc]
正在解析 java… [spring-boot-mvc]
java: java.lang.ArrayIndexOutOfBoundsException: 2
java: java.lang.ArrayIndexOutOfBoundsException: 2
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:239)
	at org.jetbrains.jps.javac.ExternalJavacProcess.compile(ExternalJavacProcess.java:189)
	at org.jetbrains.jps.javac.ExternalJavacProcess.access$400(ExternalJavacProcess.java:28)
	at org.jetbrains.jps.javac.ExternalJavacProcess$CompilationRequestsHandler$1.run(ExternalJavacProcess.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.supalle.autotrim.processor.AbstractTreeProcessor.matchImportType(AbstractTreeProcessor.java:504)
	at com.supalle.autotrim.processor.AbstractTreeProcessor.visitClass(AbstractTreeProcessor.java:147)
	at com.supalle.autotrim.processor.AbstractTreeProcessor.visitClass(AbstractTreeProcessor.java:26)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
	at com.supalle.autotrim.AutoTrimProcessor.finishRemaining(AutoTrimProcessor.java:120)
	at com.supalle.autotrim.AutoTrimProcessor.process(AutoTrimProcessor.java:91)
	at org.jetbrains.jps.javac.APIWrappers$ProcessorWrapper.process(APIWrappers.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.jps.javac.APIWrappers$1.invoke(APIWrappers.java:362)
	at com.sun.proxy.$Proxy7.process(Unknown Source)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 9 more
正在检查依赖项… [spring-boot-mvc]
依赖分析发现 0 个受影响的文件
编译模块 'spring-boot-mvc' 时发生错误
javac 8 用于编译 java 源
已完成，正在保存缓存…
编译失败: 错误: 2；警告: 0
执行后编译任务…
编译失败: 错误: 2；警告: 0
正在同步输出目录…
2023/4/23 17:22 - 编译完成6秒547毫秒中 2 个错误 和 0 个警告
```

**Comment by supalle** [comment]
我试一下哈

**Comment by supalle** [comment]
我可以正常编译哎，方便问下你是什么操作系统，那一版的jdk吗？
![image](https://user-images.githubusercontent.com/54652851/233836072-97698715-1097-4ffc-8151-cad8703c0108.png)

**Comment by supalle** [comment]
应该是我这几行代码有问题，太粗心了，我好好看看
```java
boolean hasSuffix = names.length > 1 && names[2].trim().length() > 0;
            String firstSimpleNameAndPrefix = "." + firstSimpleName;
            if (hasSuffix) {
                String suffix = "." + names[2].trim();
                for (String pkg : packages) {
                    if (pkg.equals(firstSimpleName) || pkg.endsWith(firstSimpleNameAndPrefix)) {
                        Symbol.ClassSymbol typeElement = elementUtils.getTypeElement(pkg + suffix);
                        if (typeElement != null && typeName.equals(typeElement.asType().toString())) {
                            return classMetadata.cacheTypeMatchResult(typeName, annotationTypeName, true);
                        }
                    }
                }
            }
```

**Comment by easycnn** [comment]
windows+jdk8_332。 控制器里方法加上注解就不会引发这个问题。因为我做测试把控制器里代码注释掉了。就导致无法启动。

**Comment by supalle** [comment]
问题已经修复了，但是打包发布，还得晚一些，估计晚上才同步到Maven中央仓库

**Comment by supalle** [comment]
已经发布了修复的版本 1.0.1到中央仓库，你可以使用试一下；
```xml
<dependency>
    <groupId>com.supalle</groupId>
    <artifactId>auto-trim</artifactId>
    <version>1.0.1</version>
    <!-- <optional>true</optional> -->
    <scope>provided</scope>
</dependency>
```

**Comment by supalle** [comment]
如何了？问题解决了吗？解决了我就关闭这个issue了

**Comment by supalle** [comment]
应该是修复了的，我最近还排查了一下其它的，发布了V1.0.2，您可以使用最新的
